name: Auto-Assign Navi-04 as Reviewer

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assign @navi-04 as reviewer
        uses: actions/github-script@v6
        with:
          script: |
            const reviewer = 'navi-04';
            const prNumber = context.payload.pull_request.number;
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              reviewers: [reviewer]
            });
